# generated by datamodel-codegen:
#   filename:  analysis-completed.schema.json
#   timestamp: 2026-09-15T01:17:11+00:00

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field, confloat, conint


class AnalysisCompletedEvent(BaseModel):
    analysis_id: UUID = Field(..., alias='analysisId')
    result: dict[str, Any]
    source_page: conint(ge=0) | None = Field(None, alias='sourcePage')
    confidence: confloat(ge=0.0, le=1.0) | None = None
