# generated by datamodel-codegen:
#   filename:  analysis-requested.schema.json
#   timestamp: 2026-09-15T01:17:05+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class Type(Enum):
    summary = 'SUMMARY'
    extract_values = 'EXTRACT_VALUES'
    deadlines = 'DEADLINES'
    compare = 'COMPARE'


class AnalysisRequestedEvent(BaseModel):
    analysis_id: UUID = Field(..., alias='analysisId')
    document_id: UUID = Field(..., alias='documentId')
    user_id: UUID = Field(..., alias='userId')
    type: Type
