# generated by datamodel-codegen:
#   filename:  analysis-completed.schema.json
#   timestamp: 2026-09-15T01:17:11+00:00

from __future__ import annotations

from typing import Annotated, Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class AnalysisCompletedEvent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    analysis_id: UUID = Field(..., alias="analysisId")
    result: dict[str, Any]
    source_page: Annotated[int, Field(ge=0)] | None = Field(None, alias="sourcePage")
    confidence: Annotated[float, Field(ge=0.0, le=1.0)] | None = None