# generated by datamodel-codegen:
#   filename:  document-uploaded.schema.json
#   timestamp: 2026-09-15T01:16:23+00:00

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class FileType(Enum):
    pdf = 'PDF'
    docx = 'DOCX'
    xlsx = 'XLSX'


class DocumentUploadedEvent(BaseModel):
    document_id: UUID = Field(..., alias='documentId')
    user_id: UUID = Field(..., alias='userId')
    storage_url: str = Field(..., alias='storageUrl')
    file_type: FileType = Field(..., alias='fileType')
