# generated by datamodel-codegen:
#   filename:  document-embedded.schema.json
#   timestamp: 2026-09-15T01:16:59+00:00

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field, conint


class DocumentEmbeddedEvent(BaseModel):
    document_id: UUID = Field(..., alias='documentId')
    chunks_count: conint(ge=1) = Field(..., alias='chunksCount')
