# generated by datamodel-codegen:
#   filename:  document-embedded.schema.json
#   timestamp: 2026-09-15T01:16:59+00:00

from __future__ import annotations

from typing import Annotated
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class DocumentEmbeddedEvent(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    document_id: UUID = Field(..., alias="documentId")
    chunks_count: Annotated[int, Field(ge=1)] = Field(..., alias="chunksCount")