"""create rag tables

Revision ID: b924c07c0193
Revises: 
Create Date: 2026-09-14 23:20:04.532040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b924c07c0193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='rag')
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False, schema='rag')
    op.create_index(op.f('ix_rag_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False, schema='rag')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['rag.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='rag'
    )
    op.create_index(op.f('ix_rag_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False, schema='rag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_chat_messages_session_id'), table_name='chat_messages', schema='rag')
    op.drop_table('chat_messages', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_user_id'), table_name='document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_document_chunks_document_id'), table_name='document_chunks', schema='rag')
    op.drop_table('document_chunks', schema='rag')
    op.drop_index(op.f('ix_rag_chat_sessions_user_id'), table_name='chat_sessions', schema='rag')
    op.drop_table('chat_sessions', schema='rag')
    # ### end Alembic commands ###
